Repository rt-net/JetsonNanoMouse, pull requests merged in 2021-11, with the labels that each got.

#14 Fix installation
  README.en.md
  README.md
Labels: Type: Documentation

#17 Add external clock mode option
  README.en.md
  README.md
  drivers/rtmouse/rtmouse.c
Labels: Type: Feature

#18 Add lint CI
  .github/workflows/ci.yml
  .test/bin/run-clang-format.py
  .test/lint.sh
  drivers/rtmouse/rtmouse.c
Labels: Type: CI
